---
  host:
    description: "Hostname or IP address of the Redis instance"
    type: string
    required: true
  port:
    description: "Redis Port"
    type: integer
    default: 6379
    required: true
  database:
    description: "Database number to use"
    type: integer
    default: 0
    required: true
  password:
    description: "Password if authentication required "
    type: string
    required: false
    secret: true
